---
email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35366563626363303433313634366339613833353136343966386439616461336466663439626439
          6265613733383730383735306535633266633230343665380a643137313531333639666463313762
          38623939386364623664633963363164613531616337353938616661623434633430326465646437
          3039366531376138360a356365633465643039613433303230353135363365306532343838353133
          31643331363132316265653232333838633363346135333434666130623735643264
web_root: /var/www/html
